### ISSUE TITLE
Consider section on acceptable usage scenarios?

### ISSUE THREAD

**Issue by cipherboy** [hbs-guidance/draft-hbs-state#2]
The introduction currently contains broad language around the desirable properties of these category of algorithms:

> Their theoretic security is well understood and depends only on the security of the underlying hash function.  As such, they can serve as an important building block for quantum-resistant information and communication technology.

I think it'd benefit the broader community (especially, protocol authors looking at adding PQC into their protocols) if some of this latter phrase ("_important building block_") could be expanded upon, perhaps enumerating some scenarios in which these trade offs are acceptable.

E.g., perhaps in the scenario where potential theoretical weakness in the design of SLH-DSA or ML-DSA are an unacceptable risk to an organization (but still desires PQC security), S-HBS schemes could be considered?

**Comment by thomwiggers** [comment]
This is something that we should have a discussion about. I think that it might make sense that we recommend some evaluation criteria even, i.e., S-HBS might be appropriate IF you can't use SLH-DSA, ML-DSA, can predict the number of signatures before hand, ...

>E.g., perhaps in the scenario where potential theoretical weakness in the design of SLH-DSA 

Just quickly noting that SPHINCS+ is basically an improved XMSS (in more ways than state) (in fact, XMSS even included in the SPHINCS+ specification!), so any attack that applies to SLH-DSA will likely apply to XMSS.

**Comment by cipherboy** [comment]
> Just quickly noting that SPHINCS+ is basically an improved XMSS (in more ways than state) (in fact, XMSS even included in the SPHINCS+ specification!), so any attack that applies to SLH-DSA will likely apply to XMSS.

Ahhh, yes, this is true. I think that then strengthens the question, in what scenarios _would_ you prefer this scheme? :-)
